modLoader = "kotlinforforge"
loaderVersion = "[${versions.kotlin_neoforge_range},)"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[dependencies."${mod_id}"]]
modId = "neoforge"
type = "required"
versionRange = "[${versions.neoforge_range},)"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "[${versions.minecraft}]"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "kotlinforforge"
type = "required"
versionRange = "[${versions.kotlin_neoforge_range},)"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "owo"
type = "required"
versionRange = "[${versions.owolib},)"
ordering = "NONE"
side = "BOTH"